### PR TITLE
Moving to styled-components

### PR DESCRIPTION
**Pull request by mmahalwy**

### CODE REVIEW

**Comment by mmahalwy** [comment]
Just a few more components to go!

**Comment by mmahalwy** [comment]
@sabeurthabti okay this is ready, PTAL

**Comment by mmahalwy** [comment]
Actually, going to merge this so i can get it into this pr: https://github.com/quran/quran.com-frontend/pull/829

**Comment by thabti** [comment]
sorry bro - I didn't notice the notification. 

You're the best - looks really good.

**Comment by thabti** [comment]
We need to bring styled-components to QuranicAudio.com, only needing the SC treatment :D

**Pull request merged**
